#GENERAL
simulation_duration : 99

#EGO_VEHICLE
initial_state_x : 0.1 #0 #was 3
initial_state_y : 0 #-29.5366 #was -23
initial_state_orientation: 0
initial_state_velocity: 25 #was 9

vehicle_type : car
vehicle_length : 4.8
vehicle_width : 2
goal_point_x : -20 #40
goal_point_y : 5 #-30

#PLANNER
reference_speed : 30
max_acceleration : 5
max_deceleration : 5
planning_horizon : 60
safety_margin : 1.2

#SENSOR
field_of_view_degrees : 360
min_resolution : 1
view_range : 100

#OCCLUSION_TRACKER
occlusion_params:
  vmin : 0
  vmax : 30
  amin : -3
  amax : 2
  vlatmax : 2
  dt : 0.1
  prediction_interval : 5
  prediction_horizon : 60
  min_shadow_volume : 1.0
  mapping_quality : 1
  simplification_precision: 0.1
  velocity_tracking_enabled : False
